version: "3.3"
services: 
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017
    ports: 
      - "27017:27017"

  api:
    depends_on: 
      - mongo
    container_name: apigo
    build: .
    ports:
      - "8080:8080"
    restart: always